### ISSUE TITLE
`jiter` does not compile with the `python` feature

### ISSUE THREAD

**Issue by decorator-factory** [pydantic/jiter#125]
My Cargo.toml:
```toml
[package]
name = "scratch"
version = "0.1.0"
edition = "2021"

[dependencies]
jiter = { version = "0.5.0", features = ["python"] }
```

I get an error after running `cargo build`:
```
error[E0599]: the method `to_object` exists for reference `&BigInt`, but its trait bounds were not satisfied
   --> /home/df/.cargo/registry/src/index.crates.io-6f17d22bba15001f/jiter-0.5.0/src/number_decoder.rs:121:62
    |
121 |             Self::Int(NumberInt::BigInt(big_int)) => big_int.to_object(py),
    |                                                              ^^^^^^^^^ method cannot be called on `&BigInt` due to unsatisfied trait bounds
    |
   ::: /home/df/.cargo/registry/src/index.crates.io-6f17d22bba15001f/num-bigint-0.4.6/src/bigint.rs:57:1
    |
57  | pub struct BigInt {
    | ----------------- doesn't satisfy `BigInt: pyo3::ToPyObject`
    |
    = note: the following trait bounds were not satisfied:
            `BigInt: pyo3::ToPyObject`
            which is required by `&BigInt: pyo3::ToPyObject`

error[E0599]: the method `to_object` exists for reference `&BigInt`, but its trait bounds were not satisfied
  --> /home/df/.cargo/registry/src/index.crates.io-6f17d22bba15001f/jiter-0.5.0/src/value.rs:37:34
   |
37 |             Self::BigInt(b) => b.to_object(py),
   |                                  ^^^^^^^^^ method cannot be called on `&BigInt` due to unsatisfied trait bounds
   |
  ::: /home/df/.cargo/registry/src/index.crates.io-6f17d22bba15001f/num-bigint-0.4.6/src/bigint.rs:57:1
   |
57 | pub struct BigInt {
   | ----------------- doesn't satisfy `BigInt: pyo3::ToPyObject`
   |
   = note: the following trait bounds were not satisfied:
           `BigInt: pyo3::ToPyObject`
           which is required by `&BigInt: pyo3::ToPyObject`
```

What am I doing wrong?

System information:
- rustc 1.80.0
- Ubuntu 22.04

**Comment by samuelcolvin** [comment]
It definitely does in tests.

Cc @davidhewitt, any pointers?

**Comment by davidhewitt** [comment]
I think #126 should fix this.

**Comment by decorator-factory** [comment]
Thanks for looking into this :+1: 
this seems to work for me as a workaround
```toml
[dependencies]
jiter = { version = "0.5.0", features = ["python"]}
pyo3 = { version = "0.22.2", features = ["num-bigint"]}
```
